from datetime import datetime
from sqlalchemy import String, Float, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from app.db import Base

class PortfolioSnapshot(Base): __tablename__='portfolio_snapshots'; id:Mapped[int]=mapped_column(primary_key=True); created_at:Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); equity:Mapped[float]=mapped_column(Float, default=0)
class Position(Base): __tablename__='positions'; id:Mapped[int]=mapped_column(primary_key=True); snapshot_id:Mapped[int]=mapped_column(ForeignKey('portfolio_snapshots.id')); symbol:Mapped[str]=mapped_column(String(16)); qty:Mapped[float]=mapped_column(Float); market_value:Mapped[float]=mapped_column(Float)
class TargetAllocation(Base): __tablename__='target_allocations'; id:Mapped[int]=mapped_column(primary_key=True); symbol:Mapped[str]=mapped_column(String(16), unique=True); weight:Mapped[float]=mapped_column(Float)
class AgentRun(Base): __tablename__='agent_runs'; id:Mapped[int]=mapped_column(primary_key=True); created_at:Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); summary:Mapped[str]=mapped_column(Text, default=''); dry_run:Mapped[bool]=mapped_column(Boolean, default=False)
class AgentDecision(Base): __tablename__='agent_decisions'; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[int]=mapped_column(ForeignKey('agent_runs.id')); payload:Mapped[str]=mapped_column(Text)
class ProposedOrder(Base): __tablename__='proposed_orders'; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[int]=mapped_column(ForeignKey('agent_runs.id')); symbol:Mapped[str]=mapped_column(String(16)); side:Mapped[str]=mapped_column(String(8)); notional_usd:Mapped[float]=mapped_column(Float); approved:Mapped[bool]=mapped_column(Boolean, default=False)
class ExecutedOrder(Base): __tablename__='executed_orders'; id:Mapped[int]=mapped_column(primary_key=True); proposed_order_id:Mapped[int]=mapped_column(ForeignKey('proposed_orders.id')); external_id:Mapped[str]=mapped_column(String(64), default=''); status:Mapped[str]=mapped_column(String(32), default='submitted')
class NewsItem(Base): __tablename__='news_items'; id:Mapped[int]=mapped_column(primary_key=True); url:Mapped[str]=mapped_column(String(512), unique=True); title:Mapped[str]=mapped_column(String(512)); source:Mapped[str]=mapped_column(String(128), default=''); summary:Mapped[str]=mapped_column(Text, default=''); published_at:Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); tickers:Mapped[str]=mapped_column(String(256), default='')
class NotificationLog(Base): __tablename__='notification_logs'; id:Mapped[int]=mapped_column(primary_key=True); subject:Mapped[str]=mapped_column(String(256)); body:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class RiskRejection(Base): __tablename__='risk_rejections'; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[int]=mapped_column(ForeignKey('agent_runs.id')); symbol:Mapped[str]=mapped_column(String(16)); reason:Mapped[str]=mapped_column(String(256)); created_at:Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
